
from PySide2.QtGui import QTextDocument
from PySide2.QtWidgets import QPlainTextDocumentLayout

from ...config import Conf


class QCodeDocument(QTextDocument):
    """
    QTextDocument class for pseudocode generated by StructuredCodeGenerator analysis in angr.
    """
    def __init__(self, codegen):
        super().__init__()

        self._codegen = codegen

        # default font
        self.setDefaultFont(Conf.disasm_font)

        self.setPlainText(self._codegen.text)
        self.setDocumentLayout(QPlainTextDocumentLayout(self))

